"""mcp tokens

Revision ID: 302819f5c1dd
Revises: 2ef43a9b22e2
Create Date: 2026-10-01 17:28:40.988738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '302819f5c1dd'
down_revision: Union[str, Sequence[str], None] = '2ef43a9b22e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_token',
    sa.Column('athlete_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('athlete_id'),
    sa.UniqueConstraint('token_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mcp_token')
    # ### end Alembic commands ###
