"""phase 2: strokes, interval splits, stroke fetch queue

Revision ID: 5af8b0a7cada
Revises: fd0b181f8321
Create Date: 2026-09-16 16:06:06.148200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5af8b0a7cada'
down_revision: Union[str, Sequence[str], None] = 'fd0b181f8321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interval_split',
    sa.Column('workout_id', sa.BigInteger(), nullable=False),
    sa.Column('idx', sa.SmallInteger(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=True),
    sa.Column('time_s', sa.Numeric(precision=10, scale=1), nullable=False),
    sa.Column('distance_m', sa.Integer(), nullable=False),
    sa.Column('rest_time_s', sa.Numeric(precision=10, scale=1), nullable=False),
    sa.Column('rest_distance_m', sa.Integer(), nullable=False),
    sa.Column('spm', sa.Integer(), nullable=True),
    sa.Column('hr_avg', sa.Integer(), nullable=True),
    sa.Column('hr_max', sa.Integer(), nullable=True),
    sa.Column('hr_ending', sa.Integer(), nullable=True),
    sa.Column('hr_rest', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workout_id', 'idx')
    )
    op.create_table('stroke',
    sa.Column('workout_id', sa.BigInteger(), nullable=False),
    sa.Column('interval_idx', sa.SmallInteger(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('t_s', sa.Numeric(precision=8, scale=1), nullable=False),
    sa.Column('d_m', sa.Numeric(precision=8, scale=1), nullable=False),
    sa.Column('pace_s_500', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('spm', sa.SmallInteger(), nullable=True),
    sa.Column('hr', sa.SmallInteger(), nullable=True),
    sa.Column('is_rest', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workout_id', 'interval_idx', 'seq')
    )
    op.add_column('workout', sa.Column('stroke_status', sa.Text(), server_default='not_available', nullable=False))
    op.add_column('workout', sa.Column('stroke_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('workout', sa.Column('stroke_error', sa.Text(), nullable=True))
    op.add_column('workout', sa.Column('stroke_warning', sa.Text(), nullable=True))
    op.add_column('workout', sa.Column('strokes_fetched_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_workout_stroke_status'), 'workout', ['stroke_status'], unique=False)
    # ### end Alembic commands ###

    # Queue existing workouts. Interval splits for them are filled by `erg renormalize`.
    op.execute("UPDATE workout SET stroke_status = 'pending' WHERE has_strokes")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_stroke_status'), table_name='workout')
    op.drop_column('workout', 'strokes_fetched_at')
    op.drop_column('workout', 'stroke_warning')
    op.drop_column('workout', 'stroke_error')
    op.drop_column('workout', 'stroke_attempts')
    op.drop_column('workout', 'stroke_status')
    op.drop_table('stroke')
    op.drop_table('interval_split')
    # ### end Alembic commands ###
