"""per-athlete classification settings

Revision ID: 6cb839a8321d
Revises: a8edbe713072
Create Date: 2026-09-28 13:07:04.796291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cb839a8321d'
down_revision: Union[str, Sequence[str], None] = 'a8edbe713072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athlete', sa.Column('steady_pace_auto', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('athlete', sa.Column('steady_pace_override', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('athlete', sa.Column('interval_margin_s', sa.Numeric(precision=5, scale=1), server_default='10', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('athlete', 'interval_margin_s')
    op.drop_column('athlete', 'steady_pace_override')
    op.drop_column('athlete', 'steady_pace_auto')
    # ### end Alembic commands ###
