"""athlete profile overrides

Revision ID: 78406717f07a
Revises: 8c8eaca01a4e
Create Date: 2026-09-17 14:48:48.544517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78406717f07a'
down_revision: Union[str, Sequence[str], None] = '8c8eaca01a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athlete', sa.Column('max_heart_rate_override', sa.Integer(), nullable=True))
    op.add_column('athlete', sa.Column('weight_g_override', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('athlete', 'weight_g_override')
    op.drop_column('athlete', 'max_heart_rate_override')
    # ### end Alembic commands ###
