"""phase 4: workout metrics, daily load, rolling windows

Revision ID: 7ea07faf5b35
Revises: 78406717f07a
Create Date: 2026-09-17 15:13:36.531102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ea07faf5b35'
down_revision: Union[str, Sequence[str], None] = '78406717f07a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_load',
    sa.Column('athlete_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('work_time_s', sa.Numeric(precision=10, scale=1), nullable=False),
    sa.Column('work_distance_m', sa.Integer(), nullable=False),
    sa.Column('kj', sa.Numeric(precision=9, scale=1), nullable=True),
    sa.Column('trimp', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('athlete_id', 'date')
    )
    op.create_table('rolling_metric',
    sa.Column('athlete_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('metric_name', sa.Text(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('athlete_id', 'date', 'metric_name', 'window_days')
    )
    op.create_table('workout_metric',
    sa.Column('workout_id', sa.BigInteger(), nullable=False),
    sa.Column('ef', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('work_watts', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('work_hr', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('decoupling_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('ef_first_half', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('ef_second_half', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('pace_cv', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('spm_cv', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('first_half_pace', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('second_half_pace', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fade_onset_m', sa.Integer(), nullable=True),
    sa.Column('dps_m', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('hrr_bpm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('hrr_rest_s', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('hrr_intervals', sa.Integer(), nullable=True),
    sa.Column('kj', sa.Numeric(precision=9, scale=1), nullable=True),
    sa.Column('trimp', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metric_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workout_id')
    )
    op.add_column('athlete', sa.Column('resting_hr_override', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('athlete', 'resting_hr_override')
    op.drop_table('workout_metric')
    op.drop_table('rolling_metric')
    op.drop_table('daily_load')
    # ### end Alembic commands ###
