"""phase 3: classification and eligibility

Revision ID: 8c8eaca01a4e
Revises: 5af8b0a7cada
Create Date: 2026-09-17 14:30:17.095419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c8eaca01a4e'
down_revision: Union[str, Sequence[str], None] = '5af8b0a7cada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification_override',
    sa.Column('workout_id', sa.BigInteger(), nullable=False),
    sa.Column('workout_class', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workout_id')
    )
    op.create_table('workout_classification',
    sa.Column('workout_id', sa.BigInteger(), nullable=False),
    sa.Column('workout_class', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('classifier_version', sa.Integer(), nullable=False),
    sa.Column('classified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workout_id')
    )
    op.create_index(op.f('ix_workout_classification_workout_class'), 'workout_classification', ['workout_class'], unique=False)
    op.create_table('workout_eligibility',
    sa.Column('workout_id', sa.BigInteger(), nullable=False),
    sa.Column('metric', sa.Text(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('eligibility_version', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workout_id', 'metric')
    )
    op.create_index(op.f('ix_workout_eligibility_eligible'), 'workout_eligibility', ['eligible'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_eligibility_eligible'), table_name='workout_eligibility')
    op.drop_table('workout_eligibility')
    op.drop_index(op.f('ix_workout_classification_workout_class'), table_name='workout_classification')
    op.drop_table('workout_classification')
    op.drop_table('classification_override')
    # ### end Alembic commands ###
