"""dps from work strokes plus variability

Revision ID: a8edbe713072
Revises: 7ea07faf5b35
Create Date: 2026-09-17 15:41:17.624792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8edbe713072'
down_revision: Union[str, Sequence[str], None] = '7ea07faf5b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_metric', sa.Column('dps_cv', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('workout_metric', sa.Column('dps_source', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_metric', 'dps_source')
    op.drop_column('workout_metric', 'dps_cv')
    # ### end Alembic commands ###
