"""phase 1: athlete, oauth_token, workout

Revision ID: fd0b181f8321
Revises: 
Create Date: 2026-09-16 13:20:56.253812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd0b181f8321'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('max_heart_rate', sa.Integer(), nullable=True),
    sa.Column('weight_g', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('dob', sa.Text(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_token',
    sa.Column('athlete_id', sa.BigInteger(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('athlete_id')
    )
    op.create_table('workout',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('athlete_id', sa.BigInteger(), nullable=False),
    sa.Column('ended_at_local', sa.DateTime(), nullable=False),
    sa.Column('ended_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tz', sa.Text(), nullable=False),
    sa.Column('tz_source', sa.Text(), nullable=False),
    sa.Column('started_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('machine', sa.Text(), nullable=True),
    sa.Column('workout_type', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('work_time_s', sa.Numeric(precision=10, scale=1), nullable=False),
    sa.Column('work_distance_m', sa.Integer(), nullable=False),
    sa.Column('rest_time_s', sa.Numeric(precision=10, scale=1), nullable=False),
    sa.Column('rest_distance_m', sa.Integer(), nullable=False),
    sa.Column('avg_spm', sa.Integer(), nullable=True),
    sa.Column('stroke_count', sa.Integer(), nullable=True),
    sa.Column('drag_factor', sa.Integer(), nullable=True),
    sa.Column('avg_pace_s_500', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('avg_watts', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('watts_derived', sa.Boolean(), nullable=False),
    sa.Column('hr_avg', sa.Integer(), nullable=True),
    sa.Column('hr_ending', sa.Integer(), nullable=True),
    sa.Column('hr_rest', sa.Integer(), nullable=True),
    sa.Column('hr_quality', sa.Text(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('has_strokes', sa.Boolean(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'ended_at_local', 'work_time_s', 'work_distance_m', name='uq_workout_c2_dedupe')
    )
    op.create_index(op.f('ix_workout_athlete_id'), 'workout', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_workout_ended_at_utc'), 'workout', ['ended_at_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_ended_at_utc'), table_name='workout')
    op.drop_index(op.f('ix_workout_athlete_id'), table_name='workout')
    op.drop_table('workout')
    op.drop_table('oauth_token')
    op.drop_table('athlete')
    # ### end Alembic commands ###
